### ISSUE TITLE
How to preprocess audio files for Multimodal Speech Emotion Recognition

### ISSUE THREAD

**Issue by Bharath1991999** [shamanez/MAIA-Data-Processing#7]
I recently trained Multimodal Emotion Recogntion with pretreined Roberta and Speech-BERT and want to check the emotions for the **.wav** audios

But I have seen for preprocessing you have used raw audio files of **.pt format** which I have never listened before
**audio_files = sorted(glob.glob(audio_path+"*.pt"))**

Can you please help me to know about **.pt format** and help me understand how to preprocess **.wav** audio files

**Comment by shamanez** [comment]
.pt files means just the numpy arrays saved after reading wav files. It is
not actually a file format.

**Comment by Bharath1991999** [comment]
Thankyou
